[package]
name = "hamiltonienhubbard_exemple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
#lto = "thin"
panic = "abort"
opt-level = 3
incremental = true
codegen-units = 1
